config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'activities#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
  # API Routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post '/login', to: 'login#login'
      post 'favorite', to: 'activities#favorite'
      post 'unfavorite', to: 'activities#unfavorite'
      get 'favorites', to: 'users#favorites'  
      resources :activities, only: [ :index, :show, :update, :unfavorite, :favorited ] do
        resources :bookings, only: [ :index, :show, :create, :update ]
        resources :users, only: [ :index, :show ]
      end
      resources :users, only: [ :index, :show ] do
        resources :bookings, only: [ :index, :show, :create, :update ]
      end
      resources :instructors, only: [ :index, :show ]
    end
  end
  
  
  # Website Routes
  resources :activities do
    resources :sessions
  end

  resources :bookings

  resources :instructors

  resources :users do
    resources :bookings
    resources :instructors
    resources :activities
  end
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  belongs_to :user
  has_many :sessions

  has_one_attached :profile_pic

  # in the future, users can favorite instructors
  # acts_as_favoritable
end

app/controllers/api/v1/instructors_controller.rb
class Api::V1::InstructorsController < Api::V1::BaseController
  def index
    @instructors = Instructor.all
  end

  def show
    @instructor = Instructor.find(params[:id])
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def show
  end

  def index
    @instructors = Instructor.all
  end

  def new
  end

  def create
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def update
    @instructor = Instructor.find(params[:id])
    @instructor.update(instructor_params)
    redirect_to instructors_path
  end

  private

  def instructor_params
    params.require(:instructor).permit(:user_id, :name, :years_experience, :date_started, :certifications, :verified, :blurb)
  end
end

app/views/instructors/_form.html.erb
<%= simple_form_for(@instructor) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.label :bio %>
    <%= f.text_area :blurb, { style: 'width: 100%' } %>
    <%= f.input :certifications %>
    <%= f.input :verified %>
    <%= f.input :date_started %>
  </div>

  <div class="form-actions my-2">
    <%= f.submit ("Submit"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Instructors#edit</h1>
<p>Find me in app/views/instructors/edit.html.erb</p>

app/views/instructors/index.html.erb
<div class="container mt-2">
  <h1>Instructors index</h1>
  <% @instructors.each do |instructor| %>

    <div class="card w-75 my-1">
      <div class="card-body">
        <h5 class="card-title"><%= instructor.name %></h5>
        <div class="d-flex">
          <div class="container">
            <p class="card-text"><%= instructor.years_experience %> years experience</p>
            <p class="card-text">Started at: <%= instructor.date_started %></p>
            <p class="card-text">Bio: <%= instructor.blurb %></p>
            <p class="card-text">Certifications: <%= instructor.certifications %></p>
          </div>
          <div>
            <%= image_tag instructor.profile_pic, class: "avatar" %>
            <%#= link_to 'Edit', edit_instructor_path(@instructor), class: "btn btn-primary btn-lg", role: "button" %>
          </div>
        </div>
      </div>
    </div>
    
  <% end %>
</div>

app/views/instructors/new.html.erb
<h1>Instructors#new</h1>
<p>Find me in app/views/instructors/new.html.erb</p>

app/views/instructors/show.html.erb
<h1>Instructors#show</h1>
<p>Find me in app/views/instructors/show.html.erb</p>

app/views/instructors/update.html.erb
<h1>Instructors#update</h1>
<p>Find me in app/views/instructors/update.html.erb</p>