config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'activities#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
  # API Routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post '/login', to: 'login#login'
      post 'favorite', to: 'activities#favorite'
      post 'unfavorite', to: 'activities#unfavorite'
      get 'favorites', to: 'users#favorites'  
      resources :activities, only: [ :index, :show, :update, :unfavorite, :favorited ] do
        resources :bookings, only: [ :index, :show, :create, :update ]
        resources :users, only: [ :index, :show ]
      end
      resources :users, only: [ :index, :show ] do
        resources :bookings, only: [ :index, :show, :create, :update ]
      end
      resources :instructors, only: [ :index, :show ]
    end
  end
  
  
  # Website Routes
  resources :activities do
    resources :sessions
  end

  resources :bookings

  resources :instructors

  resources :users do
    resources :bookings
    resources :instructors
    resources :activities
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to activities_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "My Instructors", instructors_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "My Activities", activities_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Admin", "/admin", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%#= link_to "My Profile", "#", class: "dropdown-item" %>
            <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>