config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'activities#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
  # API Routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post '/login', to: 'login#login'
      post 'favorite', to: 'activities#favorite'
      post 'unfavorite', to: 'activities#unfavorite'
      get 'favorites', to: 'users#favorites'  
      resources :activities, only: [ :index, :show, :update, :unfavorite, :favorited ] do
        resources :bookings, only: [ :index, :show, :create, :update ]
        resources :users, only: [ :index, :show ]
      end
      resources :users, only: [ :index, :show ] do
        resources :bookings, only: [ :index, :show, :create, :update ]
      end
      resources :instructors, only: [ :index, :show ]
    end
  end
  
  
  # Website Routes
  resources :activities do
    resources :sessions
  end

  resources :bookings

  resources :instructors

  resources :users do
    resources :bookings
    resources :instructors
    resources :activities
  end
end

app/models/activity.rb
require 'open-uri'

class Activity < ApplicationRecord
  before_commit :set_default_photo

  belongs_to :organizer, class_name: "User", foreign_key: :user_id
  has_many :sessions, dependent: :destroy
  has_one_attached :main_photo
  has_one_attached :photo_1
  has_one_attached :photo_2
  has_one_attached :photo_3

  acts_as_taggable_on :tags
  acts_as_favoritable

  include PgSearch::Model
  pg_search_scope :global_search,
  against: [:title, :description],
  associated_against: {
    organizer: [:name]
  },
  using: {
    tsearch: { prefix: true }
  }

  def set_default_photo
    photo_1.attach(io: File.open("app/assets/images/no_photo-03.png"), filename: "default.jpg", content_type: "image/jpg") if photo_1.blank?
    photo_2.attach(io: File.open("app/assets/images/no_photo-03.png"), filename: "default.jpg", content_type: "image/jpg") if photo_2.blank?
    photo_3.attach(io: File.open("app/assets/images/no_photo-03.png"), filename: "default.jpg", content_type: "image/jpg") if photo_3.blank?
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    ## check if activity.main_photo.blank?
    ### @activty_url = ....
    @activities = Activity.includes(:sessions)

    query = params[:query]
    if query.present?
      @activities = Activity.global_search(query)
    else
      @activities = Activity.all.order("created_at DESC")
    end
  end

  def new
    @activity = Activity.new
  end

  def create
    @user = current_user
    @activity = Activity.new(activity_params)
    @activity.organizer = @user
    @activity.save
    # raise
    redirect_to activities_path
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    @activity.update(activity_params)
    redirect_to activity_path(@activity)
  end

  def show
    @activity = Activity.find(params[:id])
    @sessions = @activity.sessions.order("start_time ASC")
  end

  def remove_tag
    @activity.tag_list.remove(params[:tag])
    @activity.save!

    # redirect_to activities_path(@activity)
  end

  def tagged
    if params[:tag].present?
      @activities = Activity.tagged_with(params[:tag])
    else
      @activities = Activity.all
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:title, :description, :main_photo, :photo_1, :photo_2, :photo_3, :price, :rating, :address, :latitude, :longitude, :tag_list)
  end
end

app/controllers/api/v1/activities_controller.rb
class Api::V1::ActivitiesController < Api::V1::BaseController
  skip_before_action :verify_authenticity_token

  def index
    query = params[:query]
    if query.present?
      @activities = Activity.global_search(query)
      # @activities = Activity.joins(:organizer).where("title ILIKE :query, description ILIKE :query, organizers.name ILIKE :query", query: "%#{query}%")
    else
      @activities = Activity.all.order("created_at DESC")
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @sessions = @activity.sessions.order("start_time ASC")
    @user = User.find(params[:user_id])
  end

  def favorite
    activity = Activity.find(params[:id])
    user = User.find(params[:user_id])
    user.favorited?(activity) ? user.unfavorite(activity) : user.favorite(activity)
    render json: {favorited: user.favorited?(activity)}
  end

  def unfavorite
    activity = Activity.find(param[:id])
    user = User.find(params[:user_id])
    user.unfavorite(activity)
  end

  def favorited
    user = User.find(params[:user_id])
    user.all_favorited
  end
end

app/views/activities/_form.html.erb
<%= simple_form_for(@activity) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.label :description %>
    <%= f.text_area :description, { style: 'width: 100%' } %>
    <%= f.input :address %>
    <%#= f.input :requirements %>
    <%= f.input :main_photo %>
    <div class="d-flex">
      <%= f.input :photo_1 %>
      <%= f.input :photo_2 %>
      <%= f.input :photo_3 %>
    </div>
    <%#= f.input :tag_list, collection: Tag.all, input_html: { multiple: true, style: 'width: 100%', label: "Choose some tags" }, include_hidden: false %>
  </div>

  <div class="form-actions my-2">
    <%= f.submit ("Submit"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<div class="container w-75">
  <h1>Edit Activity</h1>
  
  <%= render 'form', activity: @activity %>
  
  <%= link_to 'Index', activities_path %> |
  <%= link_to 'Back', activity_path %>
</div>

app/views/activities/index.html.erb
<div class="container">
  <div>
    <h1 class="my-2">Activities Index</h1>
    <%= link_to 'Create an activity', new_activity_path, class: "btn btn-primary my-3", role: "button" %>
  </div>
  
  <div class="row row-cols-1 row-cols-md-2">

    <% @activities.each do |activity| %>

      <%= link_to activity, style: "text-decoration: none; color: black" do %>
        <div class="col mb-4">
          <div class="card">
            <%= image_tag activity.main_photo, class: "card-img-top"  %>
            <div class="card-body">
              <h5 class="card-title"><%= activity.title %></h5>
              <h6><%= activity.organizer.name %></h6>
              <p class="card-text"><%= activity.description.truncate(180, :separator => ' ') %></p>
              <p class="card-address"><%= activity.address %></p>
            </div>
          </div>        
        </div>
      <% end  %>

    <% end %>

  </div>
</div>

app/views/activities/new.html.erb
<div class="container w-75 my-3">
  <h1 class="mt-3">Add an Activity</h1>
  
  <%= render 'form', activity: @activity %>
  
  <%= link_to 'Index', activities_path %>
</div>

app/views/activities/show.html.erb
<div class="container w-75 mt-4">
  <div class="jumbotron">
    <%# <span class="small">id:  %>
    <%#= @activity.id</span> %>
    <h1 class="display-4"><%= @activity.title %></h1>

    <p class="lead">Organized by <%= @activity.organizer.name %></p>
    <p><%= @activity.address %></p>
    <hr class="my-4">
    <p><%= @activity.description %></p>

    <%# @activity.tag_list.each do |tag| %>
      <%# <span> %>
        <%#= link_to tag, tagged_activities_path(tag: tag) %>
      <%# </span> %>
    <%# end %>

    <%= link_to 'Edit', edit_activity_path(@activity), class: "btn btn-primary btn-lg", role: "button" %>
  </div>

  <h2>Photo Gallery</h2>
  <div class="container w-100 mb-5">
    <div class="row row-cols-1 row-cols-md-2">
      <%= image_tag @activity.main_photo, class: "border border-primary" %>
      <% unless @activity.photo_1.blank? %>
        <%= image_tag @activity.photo_1, class: "" %>
      <% end %>
      <% unless @activity.photo_2.blank? %>
        <%= image_tag @activity.photo_2, class: "" %>
      <% end %>
      <% unless @activity.photo_3.blank? %>
        <%= image_tag @activity.photo_3, class: "" %>
      <% end %>
    </div>
  </div>

  <div class="container">
    <h2>Sessions for this activity</h2>
    <% @activity.sessions.each do |session| %>

      <div class="card w-75 my-1">
        <div class="card-body">
          <h5 class="card-title"><%= session.title %></h5>
          <p class="card-text"><%= session.instructor.name %></p>
          <p class="card-text">From: <%= session.start_time %>   to: <%= session.end_time.hour %>:<%= session.end_time.min %>0</p>
          <p class="card-text">Capacity <%= session.capacity %></p>
        </div>
      </div>
      
    <% end %>
  </div>
</div>  